<template>
    <div class="dashboardUserBento__base">
        <div class="dashboardUserBento__topGrid">
            <div class="dashboardUserBento__topGridItem">
                <h1 class="h2">Dashboard</h1>
                <div class="card card--primary flex">
                    <img
                        src="/imgs/3d-chart.png"
                        alt="3D illustration pie chart"
                        class="dashboardUserBento__topGridItem--image"
                    />
                    <div class="dashboardUserBento__subText">
                        <h2 class="d2">Some Important Title</h2>
                        <p class="text">
                            Lorem ipsum, dolor sit amet consectetur adipisicing
                            elit. Dolor earum doloribus possimus consequuntur,
                            iusto quod, soluta aperiam sint deserunt ducimus
                            sapiente, aspernatur eum excepturi repellat illum!
                            Architecto nesciunt autem neque.
                        </p>
                    </div>
                </div>
            </div>
            <div
                class="card dashboardUserBento__topGridItem dashboardUserBento__userCard"
            >
                <img
                    src="/imgs/profile-photo.png"
                    alt="User avatar generated by CHATGPT"
                    class="dashboardUserBento__userCard--userImage"
                />

                <div class="dashboardUserBento__userCard--userInfo">
                    <span class="h3">{{ userName }}</span>

                    <div
                        class="dashboardUserBento__userCard--userFundsContainer"
                    >
                        <span class="textXL">Prostředky:</span>
                        <span class="textXL--bold">{{ userFunds }} Kč</span>
                    </div>
                </div>

                <button class="btn btn--primary">Dobít prostředky</button>
            </div>
        </div>
        <div class="dashboardUserBento__bottomGrid">
            <div
                v-for="(item, index) in bottomGridItems"
                :key="index"
                class="dashboardUserBento__bottomGridItem"
            >
                <div class="card card--secondary">
                    <img :src="`/imgs/${item.icon}`" alt="icon" />
                    <h3 class="h3">{{ item.title }}</h3>
                    <span class="arrow">&rarr;</span>
                </div>
            </div>
        </div>
    </div>
</template>

<script setup>
const bottomGridItems = ref([
    { icon: "action-icon-01.svg", title: "Přidejte inzerát" },
    { icon: "action-icon-02.svg", title: "Sparovat portál" },
    { icon: "action-icon-03.svg", title: "Vaše inzeráty" },
]);

const userName = "Jana Nováková";
const userFunds = 5000000;
</script>

<style lang="scss" scoped>
@import "@/assets/styles/_breakpoints.scss";
.dashboardUserBento {
    &__base {
        display: flex;
        flex-direction: column;
        gap: 32px;

        .btn--primary {
            font-size: 1.2rem;
            width: 100%;
            height: 50px;
            justify-content: center;
            cursor: pointer;
        }
    }

    &__topGrid {
        display: flex;
        flex-direction: column;
        gap: 16px;

        @include lg {
            display: grid;
            grid-template-areas: "mainItem mainItem user";
            grid-template-columns: 1fr 1fr 1fr;
        }

        &Item {
            display: flex;
            flex-direction: column;
            gap: 8px;

            &--image {
                display: none;

                @include lg {
                    display: block;
                    width: 300px;
                    height: 300px;
                }
            }

            &:nth-child(1) {
                grid-area: mainItem;
            }

            &:nth-child(2) {
                grid-area: user;
            }
        }
    }

    &__userCard {
        display: flex;
        flex-direction: column;
        align-items: flex-start;
        text-align: left;

        &--userImage {
            border-radius: 50%;
            width: 200px;
            height: 200px;
        }

        &--userInfo {
            width: 100%;
        }

        &--userFundsContainer {
            display: flex;
            justify-content: space-between;
            width: 100%;
            margin: 20px 0px;
        }
    }

    &__subText {
        color: $c-white;
        display: grid;
        grid-template-rows: auto auto;
        justify-items: start;
        text-align: left;
        margin-left: 20px;
        margin-bottom: 20px;
    }

    &__bottomGrid {
        display: flex;
        flex-direction: column;
        gap: 32px;

        @include lg {
            display: grid;
            grid-template-columns: repeat(3, 1fr);
        }

        &Item {
            .card {
                display: flex;
                flex-direction: column;
                justify-content: center;
                align-items: center;
                padding: 20px;
                position: relative;
                min-height: 300px;

                img {
                    margin-bottom: 10px;
                    width: 170px;
                    height: 170px;
                }

                .arrow {
                    position: absolute;
                    bottom: 10px;
                    right: 10px;
                    font-size: 1.2rem;
                }
            }
        }
    }
}
</style>
